### ISSUE TITLE
Does it work in windows?

### ISSUE THREAD

**Issue by DemianTinkiel** [AnObfuscator/WireMockManager#3]
Hi,

I've setup  python 2.7.11 in a win7x64 machine and installed wmm
I've setup a folder with wmm setup but when I try to record or mocj anything I get
`
Traceback (most recent call last):
  File "C:\Python27\Scripts\wmm-script.py", line 9, in <module>
    load_entry_point('WireMock-Manager==0.0.1.dev1', 'console_scripts', 'wmm')()
  File "build\bdist.win32\egg\wiremockmanager\wmm.py", line 173, in main
  File "build\bdist.win32\egg\argh\helpers.py", line 55, in dispatch
  File "build\bdist.win32\egg\argh\dispatching.py", line 174, in dispatch
  File "build\bdist.win32\egg\argh\dispatching.py", line 277, in _execute_command
  File "build\bdist.win32\egg\argh\dispatching.py", line 260, in _call
  File "build\bdist.win32\egg\wiremockmanager\wmm.py", line 13, in wrapper
  File "build\bdist.win32\egg\wiremockmanager\wmm.py", line 23, in wrapper
  File "build\bdist.win32\egg\wiremockmanager\wmm.py", line 73, in record
  File "build\bdist.win32\egg\wiremockmanager\wmm.py", line 160, in _print_table
  File "build\bdist.win32\egg\wiremockmanager\wiremock.py", line 60, in as_list
  File "build\bdist.win32\egg\wiremockmanager\wiremock.py", line 74, in _extract_params
`

Did you ever test/intended it to work in Windows?

**Comment by AnObfuscator** [comment]
Hi, I have never tested it in Windows, as I work entirely in OS X and Linux. I don't even have a Windows box available to test with.
